// Generated by gencpp from file logitech_cam/ImageSrv.msg
// DO NOT EDIT!


#ifndef LOGITECH_CAM_MESSAGE_IMAGESRV_H
#define LOGITECH_CAM_MESSAGE_IMAGESRV_H

#include <ros/service_traits.h>


#include <logitech_cam/ImageSrvRequest.h>
#include <logitech_cam/ImageSrvResponse.h>


namespace logitech_cam
{

struct ImageSrv
{

typedef ImageSrvRequest Request;
typedef ImageSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageSrv
} // namespace logitech_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::logitech_cam::ImageSrv > {
  static const char* value()
  {
    return "ba55116f263d40ea8759822097ad63d4";
  }

  static const char* value(const ::logitech_cam::ImageSrv&) { return value(); }
};

template<>
struct DataType< ::logitech_cam::ImageSrv > {
  static const char* value()
  {
    return "logitech_cam/ImageSrv";
  }

  static const char* value(const ::logitech_cam::ImageSrv&) { return value(); }
};


// service_traits::MD5Sum< ::logitech_cam::ImageSrvRequest> should match
// service_traits::MD5Sum< ::logitech_cam::ImageSrv >
template<>
struct MD5Sum< ::logitech_cam::ImageSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::logitech_cam::ImageSrv >::value();
  }
  static const char* value(const ::logitech_cam::ImageSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::logitech_cam::ImageSrvRequest> should match
// service_traits::DataType< ::logitech_cam::ImageSrv >
template<>
struct DataType< ::logitech_cam::ImageSrvRequest>
{
  static const char* value()
  {
    return DataType< ::logitech_cam::ImageSrv >::value();
  }
  static const char* value(const ::logitech_cam::ImageSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::logitech_cam::ImageSrvResponse> should match
// service_traits::MD5Sum< ::logitech_cam::ImageSrv >
template<>
struct MD5Sum< ::logitech_cam::ImageSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::logitech_cam::ImageSrv >::value();
  }
  static const char* value(const ::logitech_cam::ImageSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::logitech_cam::ImageSrvResponse> should match
// service_traits::DataType< ::logitech_cam::ImageSrv >
template<>
struct DataType< ::logitech_cam::ImageSrvResponse>
{
  static const char* value()
  {
    return DataType< ::logitech_cam::ImageSrv >::value();
  }
  static const char* value(const ::logitech_cam::ImageSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOGITECH_CAM_MESSAGE_IMAGESRV_H
